### ISSUE TITLE
Shielded Catcher

### ISSUE THREAD

**Issue by TeamSpen210** [BEEmod/tspenAddons#15]
A laser catcher with small protrusions on the sides to prevent activating it from very oblique angles.
- Art Therapy has a laser catcher recessed into the wall, with no walls to the side.

**Comment by Luke18033** [comment]
I think the recessed version would look better for most styles. Why only on Art Therapy?

**Comment by Luke18033** [comment]
This issue was moved to BEEmod/BEE2-items#1476
