### ISSUE TITLE
Coop Dropper

### ISSUE THREAD

**Issue by TeamSpen210** [BEEmod/tspenAddons#19]
A version of the player droppers that can be controlled by the mapmaker.
On trigger (similar to autoportals) others deactivate and then they activate.
Embeds 3 blocks up

3 types:
- Orange-only
- Blue-only
- Both (both players will spawn from this, at slightly different heights to enable both simultaneously spawning.

**Comment by Luke18033** [comment]
This has been implemented in BEE2.4. :)
