### ISSUE TITLE
Pacific neurotoxin

### ISSUE THREAD

**Issue by prrg** [BEEmod/tspenAddons#22]
I expect that this is not dead >.<

Well, I downloaded your mod and everything went great, the problem is with Neurotoxin Vents and Timers, the timers work almost perfectly, after cover all the test chamber, however, when the timer gets to 0, I don't die, I tried to connect it to vents, but they're unconnectable, so I was thinking it was automatic.

So is this a bug? Or I'm not getting it right?
I'm using Refurbished style.

**Comment by Luke18033** [comment]
@prrg - This actually is pretty much dead, although all of the features will be implemented to the new [BEE2.4](https://github.com/BEEmod/BEE2.4) eventually. This is where all future improvements and fixes will occur.

**Comment by prrg** [comment]
bro this is from 2014
