### ISSUE TITLE
Monitors breaking the map

### ISSUE THREAD

**Issue by prrg** [BEEmod/tspenAddons#27]
And that's the way you find bugs on other peoples content >.<

I can't compile a map with GLaDOS Monitors, preview mode (F9) compile with no problems, preview mode with elevators and full lighting (Ctrl + F9) also compile with no problems, but compile it for publishing gives this error on console :

VVIS failed.

Valve Software - vvis.exe (Jun  4 2014)
4 threads
reading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1413398603.bsp
reading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1413398603.prt
LoadPortals: couldn't read c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1413398603.prt

That's related to the monitor, because take them off makes the publishing proceed, not only on this map, but in other maps I tried to use it.

**Comment by Luke18033** [comment]
This won't be fixed. See BEE2.4.
