### ISSUE TITLE
Cube clamp autorotate

### ISSUE THREAD

**Issue by TeamSpen210** [BEEmod/tspenAddons#3]
Add gravity detector to make the cube clamp always have the clamp appear horizontal, and drop objects straight down.

**Comment by Luke18033** [comment]
Just use `DesiredFacing`.

**Comment by TeamSpen210** [comment]
No, it's actually different - the item should have the clamp horizontal, but the cube rotating.

**Comment by Luke18033** [comment]
Should this be moved to BEE2-items?
