### ISSUE TITLE
a few bugs that i know of in latest version

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/tspenAddons#30]
BUGS
- player can fall through floor of black floor panel staircase in overgrown styles and get stuck forcing a restart of the test chamber.
- in overgrown tests the cube held by the glados extending arm with claw is in the wrong place and not aligned with the claw correctly.

**Comment by Luke18033** [comment]
These won't be fixed, unfortunately. See BEE2.4.
