### ISSUE TITLE
"Playing" status bug

### ISSUE THREAD

**Issue by IgnisWings** [BEEmod/tspenAddons#32]
Okay, now that I've been using the BEE2 a bit, I now have another problem.
SInce a week ago, every time I launch Steam, the status is stuck on "Playing: Portal 2". I've tried erasing the appcache folder and restarting, I've already returned BEE2 to Vanilla setting, and I want to know if this could be caused by BEE2 in general or only the addons?

**Comment by TeamSpen210** [comment]
Check task manger, an exe might still br running out of the Portal 2 folder perhaps. You might also want to restart your computer and see if that clears the issue. It's most likely the BEE2 itself, since these addons don't modify any of the executable code.

**Comment by IgnisWings** [comment]
@TeamSpen210 I've already restarted both Steam and my PC. I've been checking the Portal 2 folder and I don't see anything weird. Any specific .exe name I should look on the task manager to delete?

**Comment by LautaroL20** [comment]
@IgnisWings - It may be a bug related to the "Steam Sync", i have been experimented this bug related to "Playing Status", but it is not involved to Bee2 , so i think its a bug with the Steam Sync.

**Comment by IgnisWings** [comment]
@LautaroL20 You mean Steam Cloud?

**Comment by LautaroL20** [comment]
@IgnisWings - Yes.

**Comment by IgnisWings** [comment]
@LautaroL20 I've disabled it and it remains the same. Should I delete any data?

**Comment by IgnisWings** [comment]
@LautaroL20 I've disabled it and it remains the same. Should I delete any data?

**Comment by LautaroL20** [comment]
@IgnisWings - No, please do not delete any of your Steam files / games. Then it must be related to Bee2.4 wich is causing your "Playing" status bug.

**Comment by LautaroL20** [comment]
By the way, are you trying to use "TeamSpen210 Addons" into Bee2.4? This will definitelly won't work. These addons only works on "Bee2.2.5 Alpha" only.

**Comment by IgnisWings** [comment]
@LautaroL20 I'm using the Alpha version. The addons themselves work perfectly, not an error in-game.

**Comment by Luke18033** [comment]
TspenAddons wouldn't cause this, and BEE2.2 isn't being updated anymore, so if you still have this problem, then get [BEE2.4](https://github.com/BEEmod/BEE2.4)!
