### ISSUE TITLE
Suggestion: New Styles

### ISSUE THREAD

**Issue by Coolasp1e** [BEEmod/tspenAddons#33]
Ok, yes, I know I left one of these on the actual Bee Mod thing, but I didn't see this. Anyways, I want to be able to have the Underground BTS style. You know, where you go through the offices of Old Aperture and solve testlike things. It would be kinda awesome to have that style as I haven't seen a lot of chambers be able to do something close. Another good style I'd like to request is the Broken Underground style, where unused space can be turned into pits and holes. This is in a lot of chambers, but only people who know Hammer really well can do it. Just some suggestions for styles.

**Comment by CrashingScience** [comment]
See the bee2.4 github repository, this version is not current

**Comment by Luke18033** [comment]
BTS Old Aperture is already going to be implemented. Broken Old Aperture would just be an item, not a style. BEE2.2 and these addons aren't being updated anymore, suggest this on the [BEE2.4 Default Pack repository](https://github.com/BEEmod/BEE2-items).
