### ISSUE TITLE
[Suggestion] Far Future Style

### ISSUE THREAD

**Issue by QuantiX999** [BEEmod/tspenAddons#37]
What about the future Aperture Science? Maybe in the parallel universe, where it hasn't collapsed.
Neon blue chamber signs, glowing walls/panels, glass doors, creating cubes in front of players, with another words:
_**Thinking With Time Machine Style**_

**Comment by Shooba** [comment]
meh, it's a cool idea but it's pretty much just a clean style with light enhancements.

**Comment by LautaroL20** [comment]
"Far Future" Is when this suggestion gonna be implemented. TeamSpen210 have lot of bugs to fix as well as finish certain Styles before making any new style.

**Comment by Luke18033** [comment]
Looks like this has been copied to the BEE2.4 Default Pack repository. No need to keep this version open.
