### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by Shooba** [BEEmod/tspenAddons#39]
I downloaded it like 10 times already, I have BEEMOD and BEEMOD2 downloaded, and this. When I put it in the portal 2 folder, nothing happends. Or in the portal2_dlc2, etc.
Help?

**Comment by LautaroL20** [comment]
Lol you dont have to merge Bee2.4 with the Portal 2 folder. You can extract bee2.4 anywhere else, then find "Portal 2.exe", and the UI will open up.

I would recommend to verify the game cache files before anything.
