### ISSUE TITLE
I cant seem to add the new items

### ISSUE THREAD

**Issue by lextragon** [BEEmod/tspenAddons#43]
I merged the "portal2_dlc" and "sdk_content" folders from "tspenaddons_v45" in my portal 2 directory, but the new items not show up.

**Comment by LautaroL20** [comment]
You have to install Bee2.2.5 first, then extract the content from "tspenaddons_v45" into the main Portal 2 folder, then it will work.

Try deleting the "Bin", "portal2_dlc" and "sdk_content". Verify game cache files and try re-installing in the mentioned order.

**Comment by lextragon** [comment]
I have beemod 2.4.0 installed, can it work with that version ?

**Comment by TeamSpen210** [comment]
No, all the items that have been ported are included in that version already.

**Comment by lextragon** [comment]
Bit off topic: can you also tell me what the recommended custom thumbnail width and height  should be ?

**Comment by TeamSpen210** [comment]
The default screenshots are 555x312, but you can make them any size.

**Comment by lextragon** [comment]
Yeah, I tried uploading 1920x1080 but it shrink my picture to 4:3 instead of keeping it widescreen

**Comment by lextragon** [comment]
@TeamSpen210 Is there a way to avoid my thumbnail image getting changed from 16:9 to 4:3 ? The 555x312 size didn't help.

**Comment by TeamSpen210** [comment]
You can copy the image directly to the bee2 folder, the compiler just uses the file directly.

**Comment by lextragon** [comment]
thank you
