### ISSUE TITLE
Portal Deflection Cube

### ISSUE THREAD

**Issue by QuantiX999** [BEEmod/tspenAddons#45]
For some reason they doesn't respawn in global cube droppers. Wanna fix it?

**Comment by LautaroL20** [comment]
The original "TSpen Addons Pack" was part of Bee2.2.5, and @TeamSpen210 kept giving great support for it by a long period afther Vlodgi (The original author) decided to stop working on it from overnight, leaving his mod totally abandoned. Now , the current version under development by TeamSpen210 is the "Bee2.4" that has many improvements and new features. 

The latest version from Bee2.4 is the current Pre-release 21.5, you can download it, here:

The UI interface link:  https://github.com/BenVlodgi/BEE2.4/releases
The Items Packages: https://github.com/TeamSpen210/BEE2-items/releases

Feel free to participate by reporting / suggesting on the Bee2.4 Items page.

**Comment by Luke18033** [comment]
@QuantiX999 - The Global Cube Dropper currently only supports respawning vanilla cubes (Standard, Companion, Reflective, Sphere, and Frankenturret). When implemented into BEE2.4 (see @LautaroL20's comment), it will be given the ability to respawn all cubes.
