### ISSUE TITLE
Error when building map

### ISSUE THREAD

**Issue by Metodp** [BEEmod/tspenAddons#46]
Everything was fine until I installed this. Bee2 worked perfectly, but when I installed this nothing new showed up and when I tried to launch my map it said "Error building map"

Now, I want to delete this thing's files but idk how, or maybe you could fix it?

**Comment by LautaroL20** [comment]
You are using the TS Original Addons pack wich was something for the old Bee2.2.5 Alpha. This version is completely abandoned. You should use the latest version wich is Bee2.4, here are the links:

Interface: https://github.com/BenVlodgi/BEE2.4/releases
Packages: https://github.com/TeamSpen210/BEE2-items/releases

Feel free to participate giving suggestions or reporting issues, here: https://github.com/TeamSpen210/BEE2-items/issues

**Comment by Metodp** [comment]
Nope, I'm using the latest version, I installed it yesterday.

**Comment by Metodp** [comment]
Or do you mean that I can't use this mod with the newest version?

**Comment by Metodp** [comment]
![posnetek zaslona 42](https://cloud.githubusercontent.com/assets/23728603/20627576/42cfc1a6-b321-11e6-8027-0e4178959fd1.png)
I downloaded this, will it help? Is this the newest mod version?

**Comment by Metodp** [comment]
So, it didn't work, but I opened the developer console and copied all the red text

**Comment by Metodp** [comment]
[INFO] vbsp.main(): BEE2.4.0pr23 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "D:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "D:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'voice_pack': 'BEE2_GLADOS_CLEAN', 'use_screenshot': '1', 'bottomless_pit': '0'}
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Using random SP Exit (2)
[INFO] vbsp.mod_entryexit(): Using random SP Entry (3)
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (11 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[WARNING] instanceLocs._resolve(): "ITEM_BEE2_FIZZLER_OUT_RELAY" not a valid item!
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] vbsp.set_elev_videos(): Elevator type: RAND
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[WARNING] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
[INFO] voiceLine.add_voice(): Adding Base instance!
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.find_group_quotes(): "ENTRY": 1/15 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "GENERIC_1"
 | 	"choreo" "scenes/npc/glados/a2_triple_laser01.vcd"
 | 	}
 |_

[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.find_group_quotes(): "EXIT": 1/5 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line_SP"
 | 	{
 | 	"ID" "GENERIC_7"
 | 	"Choreo" "scenes/npc/glados/dlc1_leaderboard03.vcd"
 | 	}
 |_

[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.find_group_quotes(): "MIDCHAMBER": 1/9 quotes..
[INFO] voiceLine.add_voice(): 1 Mid quotes
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"Name" "Cave Reactions"
 | 	"File" "clean/cave_reaction.vmf"
 | 	}
 |_

[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] vbsp.add_screenshot_logic(): Added Screenshot Logic
[INFO] cond.core.check_all(): Map has attributes: ['spawn_dual']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=2689, misses=283, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'allowgoomist': True, 'restartonexit': True, 'fixfizzlerbump': False, 'multiversecave': True, 'rexcubepelletfizzle': False, 'nomidvoices': False, 'doorcameras': True, 'unlockdefault': False, 'bee_show_trigger': False}
[INFO] cond.core.check_all(): Global instances: {'instances/BEE2/clean/global_ents.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: False
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.change_trig(): Editing Triggers...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/video_splitter_rand.nut"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "D:\SteamLibrary\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "D:/SteamLibrary/steamapps/common/Portal 2/portal2/" "D:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): 
[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

**Comment by Metodp** [comment]
I also have the text from the error.p2c file

"portal2_puzzle"
{
	"AppID"		"644"
	"Version"		"14"
	"FileID"		"0x0000000000000000"
	"Timestamp_Created"		"0x0000000058384A0B"
	"Timestamp_Modified"		"0x0000000058384A9D"
	"CompileTime"		"15.000000"
	"Coop"		"0"
	"PreviewDirty"		"0"
	"ChamberSize"		"8 6 4"
	"Voxels"
	{
		"Solid"
		{
			"Z0"
			{
				"Y6"		"f000000000"
				"Y5"		"f000000000"
				"Y4"		"f000000000"
				"Y3"		"f000000000"
				"Y2"		"f000000000"
				"Y1"		"f000000000"
				"Y0"		"f000000000"
			}
			"Z1"
			{
				"Y6"		"f000000000"
				"Y5"		"f000000000"
				"Y4"		"f000000000"
				"Y3"		"f000000000"
				"Y2"		"f000000000"
				"Y1"		"f000000000"
				"Y0"		"f000000000"
			}
			"Z2"
			{
				"Y6"		"f000000000"
				"Y5"		"f000000000"
				"Y4"		"f000000000"
				"Y3"		"f000000000"
				"Y2"		"f000000000"
				"Y1"		"f000000000"
				"Y0"		"f000000000"
			}
			"Z3"
			{
				"Y6"		"f000000000"
				"Y5"		"f000000000"
				"Y4"		"f000000000"
				"Y3"		"f000000000"
				"Y2"		"f000000000"
				"Y1"		"f000000000"
				"Y0"		"f000000000"
			}
			"Z4"
			{
				"Y6"		"f000000000"
				"Y5"		"f000000000"
				"Y4"		"f000000000"
				"Y3"		"f000000000"
				"Y2"		"f000000000"
				"Y1"		"f000000000"
				"Y0"		"f000000000"
			}
		}
		"Portal0"
		{
			"Z0"
			{
				"Y6"		"f111110000"
				"Y5"		"f111110000"
				"Y4"		"f111111111"
				"Y3"		"f111111111"
				"Y2"		"f000111111"
				"Y1"		"f000111111"
				"Y0"		"f000111111"
			}
			"Z1"
			{
				"Y6"		"f111110000"
				"Y5"		"f111110000"
				"Y4"		"f111111111"
				"Y3"		"f111111111"
				"Y2"		"f000111111"
				"Y1"		"f000111111"
				"Y0"		"f000111111"
			}
			"Z2"
			{
				"Y6"		"f111111111"
				"Y5"		"f111111111"
				"Y4"		"f111111111"
				"Y3"		"f111111111"
				"Y2"		"f000111111"
				"Y1"		"f000111111"
				"Y0"		"f000111111"
			}
			"Z3"
			{
				"Y6"		"f111111111"
				"Y5"		"f111111111"
				"Y4"		"f111111111"
				"Y3"		"f111111111"
				"Y2"		"f111111111"
				"Y1"		"f111111111"
				"Y0"		"f111111111"
			}
			"Z4"
			{
				"Y6"		"f111111111"
				"Y5"		"f111111111"
				"Y4"		"f111111111"
				"Y3"		"f111111111"
				"Y2"		"f111111111"
				"Y1"		"f111111111"
				"Y0"		"f111111111"
			}
		}
		"Portal1"
		{
			"Z0"
			{
				"Y6"		"f111110000"
				"Y5"		"f111110000"
				"Y4"		"f111111111"
				"Y3"		"f111111111"
				"Y2"		"f000111111"
				"Y1"		"f000111111"
				"Y0"		"f000111111"
			}
			"Z1"
			{
				"Y6"		"f111110000"
				"Y5"		"f111110000"
				"Y4"		"f111111111"
				"Y3"		"f111111111"
				"Y2"		"f000111111"
				"Y1"		"f000111111"
				"Y0"		"f000111111"
			}
			"Z2"
			{
				"Y6"		"f111111111"
				"Y5"		"f111111111"
				"Y4"		"f111111111"
				"Y3"		"f111111111"
				"Y2"		"f000111111"
				"Y1"		"f000111111"
				"Y0"		"f000111111"
			}
			"Z3"
			{
				"Y6"		"f111111111"
				"Y5"		"f111111111"
				"Y4"		"f111111111"
				"Y3"		"f111111111"
				"Y2"		"f111111111"
				"Y1"		"f111111111"
				"Y0"		"f111111111"
			}
			"Z4"
			{
				"Y6"		"f111111111"
				"Y5"		"f111111111"
				"Y4"		"f111111111"
				"Y3"		"f111111111"
				"Y2"		"f111111111"
				"Y1"		"f111111111"
				"Y0"		"f111111111"
			}
		}
		"Portal2"
		{
			"Z0"
			{
				"Y6"		"f111110000"
				"Y5"		"f111110000"
				"Y4"		"f111111111"
				"Y3"		"f111111111"
				"Y2"		"f000111111"
				"Y1"		"f000111111"
				"Y0"		"f000111111"
			}
			"Z1"
			{
				"Y6"		"f111110000"
				"Y5"		"f111110000"
				"Y4"		"f111111111"
				"Y3"		"f111111111"
				"Y2"		"f000111111"
				"Y1"		"f000111111"
				"Y0"		"f000111111"
			}
			"Z2"
			{
				"Y6"		"f111111111"
				"Y5"		"f111111111"
				"Y4"		"f111111111"
				"Y3"		"f111111111"
				"Y2"		"f000111111"
				"Y1"		"f000111111"
				"Y0"		"f000111111"
			}
			"Z3"
			{
				"Y6"		"f111111111"
				"Y5"		"f111111111"
				"Y4"		"f111111111"
				"Y3"		"f111111111"
				"Y2"		"f111111111"
				"Y1"		"f111111111"
				"Y0"		"f111111111"
			}
			"Z4"
			{
				"Y6"		"f111111111"
				"Y5"		"f000000001"
				"Y4"		"f000000001"
				"Y3"		"f000000001"
				"Y2"		"f000000001"
				"Y1"		"f000000001"
				"Y0"		"f000000001"
			}
		}
	}
	"Items"
	{
		"Item"
		{
			"Index"		"0"
			"Type"		"ITEM_ENTRY_DOOR"
			"Deletable"		"0"
			"VoxelPos"		"1 0 0"
			"LocalPos"		"0 0 0"
			"Angles"		"-90 -90 0"
			"ITEM_PROPERTY_DOOR_IS_COOP"		"0"
			"Facing"		"0 0 0"
			"ConnectionVisiblity"		"0"
			"DoorInstanceID"		"2.000000"
			"Enabled"		"1"
		}
		"Item"
		{
			"Index"		"1"
			"Type"		"ITEM_COOP_ENTRY_DOOR"
			"Deletable"		"0"
			"VoxelPos"		"1 0 0"
			"LocalPos"		"0 0 0"
			"Angles"		"-90 -90 0"
			"ITEM_PROPERTY_DOOR_IS_COOP"		"0"
			"Facing"		"0 0 0"
			"ConnectionVisiblity"		"0"
			"DoorInstanceID"		"0.000000"
			"Enabled"		"0"
		}
		"Item"
		{
			"Index"		"2"
			"Type"		"ITEM_EXIT_DOOR"
			"Deletable"		"0"
			"VoxelPos"		"6 5 0"
			"LocalPos"		"0 0 0"
			"Angles"		"-90 90 0"
			"ITEM_PROPERTY_CONNECTION_COUNT"		"0"
			"ITEM_PROPERTY_START_OPEN"		"1"
			"ITEM_PROPERTY_DOOR_IS_COOP"		"0"
			"Facing"		"0 0 0"
			"ConnectionVisiblity"		"0"
			"DoorInstanceID"		"1.000000"
			"Enabled"		"1"
		}
		"Item"
		{
			"Index"		"3"
			"Type"		"ITEM_COOP_EXIT_DOOR"
			"Deletable"		"0"
			"VoxelPos"		"6 5 0"
			"LocalPos"		"0 0 0"
			"Angles"		"-90 90 0"
			"ITEM_PROPERTY_CONNECTION_COUNT"		"0"
			"ITEM_PROPERTY_DOOR_IS_COOP"		"0"
			"ITEM_PROPERTY_COOP_EXIT_STARTS_LOCKED"		"0"
			"Facing"		"0 0 0"
			"ConnectionVisiblity"		"0"
			"DoorInstanceID"		"0.000000"
			"Enabled"		"0"
		}
		"Item"
		{
			"Index"		"4"
			"Type"		"ITEM_OBSERVATION_ROOM"
			"Deletable"		"0"
			"VoxelPos"		"7 2 3"
			"LocalPos"		"0 0 0"
			"Angles"		"-90 0 0"
			"Facing"		"0 0 0"
			"ConnectionVisiblity"		"0"
		}
	}
	"Connections"
	{
		"Connection"
		{
			"Sender"		"0"
			"Receiver"		"1"
			"Type"		"CONNECTION_BARRIER_ANCHOR_TO_EXTENT"
		}
		"Connection"
		{
			"Sender"		"2"
			"Receiver"		"3"
			"Type"		"CONNECTION_BARRIER_ANCHOR_TO_EXTENT"
		}
	}
}

**Comment by Metodp** [comment]
Maybe I need to delete the old version of this mod (TeamSpen Addons)?

**Comment by Metodp** [comment]
Still doesn't work, how do I uninstall this?

**Comment by Metodp** [comment]
It doesn't even add stuff. The only thing this mod does rn is turn my Puzzle Editor to nothing :/

**Comment by LautaroL20** [comment]
Both the TS Addons pack and Bee2.2.5 are totally outdated, you can get rid of that. What you should do is download Bee2.4 and the packages trhough the links i gave you.

**Comment by Metodp** [comment]
Oooooh okay, thanks :)

**Comment by Luke18033** [comment]
You don't have to gt rid of them, you can use both. (But not at the same time)
