### ISSUE TITLE
Cube Funnel

### ISSUE THREAD

**Issue by TeamSpen210** [BEEmod/tspenAddons#9]
- A set of vphysics clips to guide a cube/ball into a button
- It should take up 128x128x64 units as an octogonal cone
- Have a player trigger 3³ blocks around it to prevent players from noticing it easily.
- The model should have the cone shape as either editor/glass or a wireframe, with the the trigger as an thin block ~16 units high at the base.

**Comment by Luke18033** [comment]
This would be useful for one of my maps, where you have to drop a cube onto a button, but it will often miss.

**Comment by Luke18033** [comment]
This issue was moved to BEEmod/BEE2-items#1478
